graphql:
  packages:
    - "com.okeicalm.simpleJournalEntry"
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    url: ${MYSQL_URL}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
logging:
  level:
    sql: "debug"